### PR TITLE
Feat - Added SetVolume command

### PR DESCRIPTION
**Pull request by ParasiteDelta**
Added SetVolume command for <you guessed it> directly setting the volume of a given input.
Takes either a raw decibel value or a percentage. If no unit is provided, interprets volume as percentage.
Added doc comment for --help.

### CODE REVIEW

**Review by jonhoo — APPROVED** [review]
This can be made a little concise using some neat tricks from `std`, but I can make those changes after the fact. Thanks!

**Comment by jonhoo** [comment]
Released in 0.1.2 :tada:

**Comment by ParasiteDelta** [comment]
> This can be made a little concise using some neat tricks from `std`, but I can make those changes after the fact. Thanks!

Eh, I needed the chance to learn. Also, `SetVolume` had the `.to_lowercase()` method as insurance in case the user just entered "db" instead of the formal "dB", which I thought should be covered given how this is a CLI. Otherwise, that clap `default_value` flag was exactly what I was hoping for initially. Back to reading.

**Comment by jonhoo** [comment]
Yeah, I realized what the `to_lowercase` was for, but decided to be strict about it since this will generally be used from scripts anyway :)

**Pull request merged**
